services:
  rabbitmq:
    container_name: rabbitmq-new
    image: rabbitmq:4-management
    ports:
      - "54321:5672"  # Host port 54321 mapped to container port 5672
      - "54322:15672"  # Host port 54322 mapped to container port 15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME} # RabbitMQ username
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD} # RabbitMQ password
