# Common properties shared across all profiles
spring.application.name=retrowalk-document-manager
server.port=5151
server.servlet.context-path=/docs

# Database configuration
url=jdbc:mysql://${HOST}:${PORT}/${DB_NAME}
username=${USERNAME}
password=${PASSWORD}
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver